global using HowToTestYourCsharpWebApi.Api;
global using HowToTestYourCsharpWebApi.Api.Adapters;
global using HowToTestYourCsharpWebApi.Api.Ports;
global using Microsoft.AspNetCore.Builder;
global using Microsoft.AspNetCore.Http;
global using System;
global using System.Linq;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;